name: 'Run Docket Tests'
description: 'Makes a request to the Docket API, waits for and reports test results'
author: 'Docket Technologies Inc.'

inputs:
  apiKey:
    description: 'Docket API key'
    required: true
  params:
    description: 'Parameters to send to the Docket API'
    required: true
    default: '{}'
  repoName:
    description: 'Name of the repository'
    required: true

outputs:
  jobId:
    description: 'The job ID of the Docket API request'

runs:
  using: 'node20'
  main: 'dist/index.js'

  env:
    DOCKET_API_KEY: ${{ inputs.apiKey }}

branding:
  icon: 'send'
  color: 'blue'
